version: '3'

services:
  omexchaindnode0:
    container_name: omexchaindnode0
    image: "omexchain/node"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-omexchaind.log}
    volumes:
      - ./build:/omexchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  omexchaindnode1:
    container_name: omexchaindnode1
    image: "omexchain/node"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-omexchaind.log}
    volumes:
      - ./build:/omexchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  omexchaindnode2:
    container_name: omexchaindnode2
    image: "omexchain/node"
    environment:
      - ID=2
      - LOG=${LOG:-omexchaind.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/omexchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  omexchaindnode3:
    container_name: omexchaindnode3
    image: "omexchain/node"
    environment:
      - ID=3
      - LOG=${LOG:-omexchaind.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/omexchaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

